 @urlApi = api.correios.com.br

POST https://{{urlApi}}/token/v1/autentica/contrato HTTP/1.1
Accept: application/json
Authorization: Basic {{accessCode}}
Content-Type: application/json

{
  "numero": "9912337526"
}

###

GET https://{{urlApi}}/cep/v2/enderecos/85070555 HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJhbWJpZW50ZSI6IlBST0RVQ0FPIiwiaWQiOiIxMzQ0MjcyNCIsInBmbCI6IlBKIiwiY25waiI6IjEwMzIyMzA0MDAwMTI5IiwiY29udHJhdG8iOnsibnVtZXJvIjoiOTkxMjMzNzUyNiIsImRyIjo3MiwiYXBpIjpbMjcsMzQsMzUsNDEsNzYsODcsNTY2XX0sImlwIjoiMjAwLjE0MC4xOTguMjI0LDIwMC4xNDAuMTk4LjIyNCIsImlhdCI6MTY5NTQ5OTk5OCwiaXNzIjoidG9rZW4tc2VydmljZSIsImV4cCI6MTY5NTU4NjM5OCwianRpIjoiODA5NmQ4YmYtNWJhYS00NjZhLTgzZjMtYzAwYzc3MGE4MmVmIn0.pi8piE4hM2J0_39tBEwL3-Ea0MtgIv_2fPQI76YmX8g9HuqHIoC3RN0mgAJjCgkWOAQJmSEWkEgLatzLHHYLtno2odX4dWzYFRKxfWu1SLSVdcBx0zp3dqkYedWeXXKyz7AQTfQ7i79-XaZWm9KYRjWpTFt5k13uLXXeB8IHaSIhtnup0BmITnsL7TmToIDqVd_P3iG_Z8uvndfnWPs2UKAwYsztJFpe3v7XwiNClXdKAwF3SCr64dJniT_fhOgtnmapyk2u7m_M8qaxZNJL8KCWYGMFNGVyRYZw5sHa6jKxkl2P3aaYTkVkhEcNW9BGjEYZLrAf8AbbERVEHkUy8A

###

GET https://{{urlApi}}/cep/v2/enderecos?cep=85070555&cep=85070200 HTTP/1.1
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzUxMiJ9.eyJhbWJpZW50ZSI6IlBST0RVQ0FPIiwiaWQiOiIxMzQ0MjcyNCIsInBmbCI6IlBKIiwiY25waiI6IjEwMzIyMzA0MDAwMTI5IiwiY29udHJhdG8iOnsibnVtZXJvIjoiOTkxMjMzNzUyNiIsImRyIjo3MiwiYXBpIjpbMjcsMzQsMzUsNDEsNzYsODcsNTY2XX0sImlwIjoiMjAwLjE0MC4xOTguMjI0LDIwMC4xNDAuMTk4LjIyNCIsImlhdCI6MTY5NTQ5OTk5OCwiaXNzIjoidG9rZW4tc2VydmljZSIsImV4cCI6MTY5NTU4NjM5OCwianRpIjoiODA5NmQ4YmYtNWJhYS00NjZhLTgzZjMtYzAwYzc3MGE4MmVmIn0.pi8piE4hM2J0_39tBEwL3-Ea0MtgIv_2fPQI76YmX8g9HuqHIoC3RN0mgAJjCgkWOAQJmSEWkEgLatzLHHYLtno2odX4dWzYFRKxfWu1SLSVdcBx0zp3dqkYedWeXXKyz7AQTfQ7i79-XaZWm9KYRjWpTFt5k13uLXXeB8IHaSIhtnup0BmITnsL7TmToIDqVd_P3iG_Z8uvndfnWPs2UKAwYsztJFpe3v7XwiNClXdKAwF3SCr64dJniT_fhOgtnmapyk2u7m_M8qaxZNJL8KCWYGMFNGVyRYZw5sHa6jKxkl2P3aaYTkVkhEcNW9BGjEYZLrAf8AbbERVEHkUy8A